### ISSUE TITLE
How to load node bound message?

### ISSUE THREAD

**Issue by mhortman** [abouillot/HomeAutomation#10]
The new updates work great.  I am able to send from node to gateway and back again to node.  Great job.

Two quick questions.
1.) How do you load up the mosquitto message to come back to the node correctly.  I load it up in OpenHab like this, but it is confusing the message (1 or 0 ) (Switch on or off) for the device.
Switch item_Garage_Light {mqtt=>[mymosquitto:RFM/101/12/1:command:ON:1],>[mymosquitto:RFM/101/12/1:command:OFF:0]"}

The message Gateway interprets this as Device 0, or Device 1 depending on if the Switch is on or off.   Can't quite figure out the correct way to send the correct ON OFF to a specific Device.

2.)  Where does the output of the sudo ./Gateway go?  It used to go to the same window that I am running sudo ./Gateway, but not does not appear.   I looked in /var/log and in the directory I am running the Gateway, but I see no log.

Thanks, Great work!

**Comment by mhortman** [comment]
OK, I have answered my own questions, I am sure there are better ways, but what I found was that by using :ON:44,1,1] instead of :ON:1] and :OFF:45,1,0] instead of :OFF:0] that the arduino picked up the device of 44 with a time of 1 (I will have to fix that) and a long value of  1
Likewise Off has device 45 with a time of 1, and a long value of 0.

As for the DEBUG, I just inserted a #define DEBUG 1 and now that works.

**Comment by abouillot** [comment]
Yes, the actual solution might not be the cleanest yet. the message part
can be built using OpenHab somehow as well, for computed values. I'm
planning to have a more flexible outbond messages to be more versatile.

Regarding debug, you can also add -dDEBUG to the command line for
compilation.
