### ISSUE TITLE
Need to enable SPI

### ISSUE THREAD

**Issue by glassl** [abouillot/HomeAutomation#12]
When I tried to run the Gateway, I got the error "Unable to open SPI device".  After some checking around, I found out that /dev/spidev0.0 didn't exist.  I followed two different blogs that had me installing all kinds of stuff, which didn't work.  Finally, I found out that the way to fix this is to run raspi-config, go to Advanced Options, then the SPI option, and then choose Yes to enable the SPI interface.  

It would be great if you could add this to the Readme.

Thanks

**Comment by abouillot** [comment]
Mention added to the readme.md file
