### ISSUE TITLE
sendACK not working properly on RasPi?

### ISSUE THREAD

**Issue by obstler42** [abouillot/HomeAutomation#2]
Thanks for the great port of the RFM69 library!

I have the piGateway running successfully and receiving messages from different sensor nodes. However I seem to have a problem with sendACK() on the Pi: when using sendWithRetry() from Arduino nodes the Arduino nodes almost never seem to receive an ACK from the Pi and always wait for the timeout and resend (tried timeouts as high as 500ms). The piGateway code calls into sendACK(), but something doesn't work properly. In a testrun with lots of sendWithRetry() the Arduinos receive an ACK maybe 1 or 2 times in 100 sends.

Does sendACK() work properly for you on the Pi?

I've also notices that the RFM69 lib has been updated after your port, but the fixes seem to be related with deadlocks and hangs.

**Comment by abouillot** [comment]
I noticed if too many traffic take place, the ACK seems lost. If the frequency of the packet remains reasonable, then all goes well.

When two nodes emit at the same time, the ACK is lost.

**Comment by obstler42** [comment]
There is almost no traffic at all (one packet every few minutes), and all normal messages go through fine -- just ACKs almost never arrive. have any RFM69 lib updates been included since your initial port?

**Comment by abouillot** [comment]
I just commit the rebase to the latest RFM69 lib. I have a test going on but so far, the node report 100% of ACK received. The ping back part doesn't see so successful unfortunately, but I see regular ACK back.

**Comment by abouillot** [comment]
The ACK might be missed by the remote side, in a similar way as some messages are lost from time to time. This might be due to specific condition, but in normal condition the lost rate is < 3% - far from the 99% reported. I will keep an eye on this, but close the issue for time being

**Comment by obstler42** [comment]
hi, I was finally able to try your latest code base (took some time to incorporate my changes again), and ACKs seem to work just fine now, great job!
