### ISSUE TITLE
issues compiling

### ISSUE THREAD

**Issue by mhortman** [abouillot/HomeAutomation#3]
g++ Gateway.c rfm69.cpp -o Gateway -lwiringPi -lmosquitto -DRASPBERRY -DDEBUG
/tmp/cc3NtBaU.o: In function `main':
Gateway.c:(.text+0x11c): undefined reference to`RFM69::initialize(unsigned char, unsigned ch\
ar, unsigned char)'
Gateway.c:(.text+0x130): undefined reference to `RFM69::setHighPower(bool)'
Gateway.c:(.text+0x144): undefined reference to`RFM69::encrypt(char const_)'
Gateway.c:(.text+0x160): undefined reference to `RFM69::promiscuous(bool)'
/tmp/cc3NtBaU.o: In function`run_loop(mosquitto_)':
Gateway.c:(.text+0x1f4): undefined reference to `RFM69::receiveDone()'
Gateway.c:(.text+0x40c): undefined reference to`RFM69::sendACK(void const*, unsigned char)'
Gateway.c:(.text+0x550): undefined reference to `RFM69::SENDERID'
Gateway.c:(.text+0x55c): undefined reference to`RFM69::TARGETID'
Gateway.c:(.text+0x564): undefined reference to `RFM69::DATA'
Gateway.c:(.text+0x56c): undefined reference to`RFM69::DATALEN'
Gateway.c:(.text+0x57c): undefined reference to `RFM69::RSSI'
Gateway.c:(.text+0x588): undefined reference to`RFM69::ACK_REQUESTED'
/tmp/cc3NtBaU.o: In function `RFM69::RFM69(unsigned char, unsigned char, bool, unsigned char)\
':
Gateway.c:(.text._ZN5RFM69C2Ehhbh[_ZN5RFM69C5Ehhbh]+0x90): undefined reference to`vtable for\
 RFM69'
Gateway.c:(.text._ZN5RFM69C2Ehhbh[_ZN5RFM69C5Ehhbh]+0x94): undefined reference to `RFM69::_mo\
de'
collect2: ld returned 1 exit status
pi@raspberrypi:~/piGateway/HomeAutomation/piGateway$ ls
Gateway.c  readme.md  rfm69.cpp  rfm69.h  rfm69registers.h

**Comment by Advanete** [comment]
Add the files listed at the bottom of your paste to the ~/piGateway directory then try to compile again.

**Comment by mhortman** [comment]
exact same error.

**Comment by Advanete** [comment]
Wrong directory?  Mine are located /home/piGateway

pi@raspberrypi ~ $ cd ~/piGateway
pi@raspberrypi ~/piGateway $ ls
Gateway  Gateway.c  readme.md  rfm69.cpp  rfm69.h  rfm69registers.h

once all files are in the correct directory, then compile

pi@raspberrypi ~/piGateway $ g++ Gateway.c rfm69.cpp -o Gateway -lwiringPi -lmosquitto -DRASPBERRY -DDEBUG

**Comment by mhortman** [comment]
I don't understand.  my directory structure looks just like your git repo
under abouillot/HomeAutomation  There is nothing in the piGateway directory
that would help this compile.  was the wiringPi compile supposed to put
some files there or what?

You say "mine are under /home/piGateway", but what does it matter?  Mine
are under /home/pi/piGateway/HomeAutomation/piGateway
I moved them to /home/pi/piGateway, and got the same error.

I have nothing under /home/piGateway

**Comment by Advanete** [comment]
No the files do not get put in the directory, which is why I asked you to
create the files or copy them from the piGateway directory on GitHub.

I ran into this same issue yesterday and I had to sudo mkdir ~/piGateway and
then created the files (Gateway.c, readme.md, rfm69.cpp, rfm69.h and
rfm69registers.h) using nano and pasted the contents of Abouillot¹s files on
GitHub (could have turned on ftp client  . . .).  I then ran the command to
compile.  I did not see any indication that the compile ran but when I
looked in the ~/piGateway directory, I saw that Gateway was included.  I
then ran it using "sudo ./Gateway²

I also followed the Readme.md from top to bottom ensuring I did not miss any
steps.  It ran first time no errors, unlike most of the tutorials I find.  I
liked it so much I starred this repository and cloned it.

Hopefully Abouillot reads this and appreciates my Thanks!

From:  mhortman notifications@github.com
Reply-To:  abouillot/HomeAutomation
<reply+0067244a34a256b96a9d7518983bc0e8e99cbbd1ac8c88c992cf00000001110b76359
2a169ce038a80b7@reply.github.com>
Date:  Sunday, March 1, 2015 at 5:52 PM
To:  abouillot/HomeAutomation HomeAutomation@noreply.github.com
Cc:  James Kirk jvkirk@advanetech.com
Subject:  Re: [HomeAutomation] issues compiling (#3)

I don't understand.  my directory structure looks just like your git repo
under abouillot/HomeAutomation  There is nothing in the piGateway directory
that would help this compile.  was the wiringPi compile supposed to put
some files there or what?

You say "mine are under /home/piGateway", but what does it matter?  Mine
are under /home/pi/piGateway/HomeAutomation/piGateway
I moved them to /home/pi/piGateway, and got the same error.

I have nothing under /home/piGateway

On Sun, Mar 1, 2015 at 4:17 PM, Advanete notifications@github.com wrote:

> Wrong directory? Mine are located /home/piGateway
> 
> pi@raspberrypi ~ $ cd ~/piGateway
> pi@raspberrypi ~/piGateway $ ls
> Gateway Gateway.c readme.md rfm69.cpp rfm69.h rfm69registers.h
> 
> once all files are in the correct directory, then compile
> 
> pi@raspberrypi ~/piGateway $ g++ Gateway.c rfm69.cpp -o Gateway
> -lwiringPi -lmosquitto -DRASPBERRY -DDEBUG
> 
> ‹
> Reply to this email directly or view it on GitHub
> https://github.com/abouillot/HomeAutomation/issues/3#issuecomment-76634561
> .

‹

**Comment by Gizzbert** [comment]
Hi, I have an issue on the next step when running the gateway; output is as follows ( Ichanged the frequency in Gateway.c to 915Mhz):
Listening at 915 Mhz...setup complete
connection refused

I can't get the "connection refused" resolved. I guess it would e related to mosquitto install, but not getting muc further with that as I have succesfully posted a msg on the bus and got an answer via 
mosquitto_sub -h localhost -v -t '#'
and
mosquitto_pub -h localhost -t test -m 'hello world'

confused now, any help/ideas?

thanks!

**Comment by abouillot** [comment]
I just tried again the gateway compilation and I'm bit puzzled.

Assuming the wiringpi library has been build previously and mosquitto has been installed.

From the home directory, I cloned the HomeAutomation tree:

 git clone git://github.com/abouillot/HomeAutomation

then compiled it without issues

 g++ Gateway.c rfm69.cpp -o Gateway -lwiringPi -lmosquitto -DRASPBERRY -DDEBUG

Look like something is missing in your case, preventing rfm69 to be properly compiled. Would it be possible to share the output of the compilation, adding -v at the end of the command line? This should give better understanding.

 g++ Gateway.c rfm69.cpp -o Gateway -lwiringPi -lmosquitto -DRASPBERRY -DDEBUG -v

Thanks advanet for the kind comment :-).

**Comment by abouillot** [comment]
Hi Gizzbert,
could you try to get the res value in the on_connect function ?

**Comment by Gizzbert** [comment]
res value was 1000 ( I think), changed it to 10 and back, still the same msg. It seems to have something to do with mosquitto (mosquitto_connect_callback_set) Will try to get that more verbose.

The verbose compiling of the gateway gave the followin result:


 g++ Gateway.c rfm69.cpp -o Gateway -lwiringPi -lmosquitto -DRASPBERRY -DDEBUG -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.6.3-14+rpi1' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.6.3 (Debian 4.6.3-14+rpi1)
COLLECT_GCC_OPTIONS='-o' 'Gateway' '-D' 'RASPBERRY' '-D' 'DEBUG' '-v' '-shared-libgcc' '-march=armv6' '-mfloat-abi=hard' '-mfpu=vfp'
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/cc1plus -quiet -v -imultilib . -imultiarch arm-linux-gnueabihf -D_GNU_SOURCE -D RASPBERRY -D DEBUG Gateway.c -quiet -dumpbase Gateway.c -march=armv6 -mfloat-abi=hard -mfpu=vfp -auxbase Gateway -version -o /tmp/cc14Rj3C.s
GNU C++ (Debian 4.6.3-14+rpi1) version 4.6.3 (arm-linux-gnueabihf)
        compiled by GNU C version 4.6.3, GMP version 5.0.5, MPFR version 3.1.0-p10, MPC version 0.9
GGC heuristics: --param ggc-min-expand=59 --param ggc-min-heapsize=55717
ignoring nonexistent directory "/usr/local/include/arm-linux-gnueabihf"
ignoring nonexistent directory "/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../arm-linux-gnueabihf/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/4.6
 /usr/include/c++/4.6/arm-linux-gnueabihf/.
 /usr/include/c++/4.6/backward
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/include
 /usr/local/include
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/include-fixed
 /usr/include/arm-linux-gnueabihf
 /usr/include
End of search list.
GNU C++ (Debian 4.6.3-14+rpi1) version 4.6.3 (arm-linux-gnueabihf)
        compiled by GNU C version 4.6.3, GMP version 5.0.5, MPFR version 3.1.0-p10, MPC version 0.9
GGC heuristics: --param ggc-min-expand=59 --param ggc-min-heapsize=55717
Compiler executable checksum: 64a5da90acce21afabe8e916f286e44e
COLLECT_GCC_OPTIONS='-o' 'Gateway' '-D' 'RASPBERRY' '-D' 'DEBUG' '-v' '-shared-libgcc' '-march=armv6' '-mfloat-abi=hard' '-mfpu=vfp'
 as -march=armv6 -mfloat-abi=hard -mfpu=vfp -meabi=5 -o /tmp/cchWEJTh.o /tmp/cc14Rj3C.s
COLLECT_GCC_OPTIONS='-o' 'Gateway' '-D' 'RASPBERRY' '-D' 'DEBUG' '-v' '-shared-libgcc' '-march=armv6' '-mfloat-abi=hard' '-mfpu=vfp'
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/cc1plus -quiet -v -imultilib . -imultiarch arm-linux-gnueabihf -D_GNU_SOURCE -D RASPBERRY -D DEBUG rfm69.cpp -quiet -dumpbase rfm69.cpp -march=armv6 -mfloat-abi=hard -mfpu=vfp -auxbase rfm69 -version -o /tmp/cc14Rj3C.s
GNU C++ (Debian 4.6.3-14+rpi1) version 4.6.3 (arm-linux-gnueabihf)
        compiled by GNU C version 4.6.3, GMP version 5.0.5, MPFR version 3.1.0-p10, MPC version 0.9
GGC heuristics: --param ggc-min-expand=59 --param ggc-min-heapsize=55717
ignoring nonexistent directory "/usr/local/include/arm-linux-gnueabihf"
ignoring nonexistent directory "/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../arm-linux-gnueabihf/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/4.6
 /usr/include/c++/4.6/arm-linux-gnueabihf/.
 /usr/include/c++/4.6/backward
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/include
 /usr/local/include
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/include-fixed
 /usr/include/arm-linux-gnueabihf
 /usr/include
End of search list.
GNU C++ (Debian 4.6.3-14+rpi1) version 4.6.3 (arm-linux-gnueabihf)
        compiled by GNU C version 4.6.3, GMP version 5.0.5, MPFR version 3.1.0-p10, MPC version 0.9
GGC heuristics: --param ggc-min-expand=59 --param ggc-min-heapsize=55717
Compiler executable checksum: 64a5da90acce21afabe8e916f286e44e
COLLECT_GCC_OPTIONS='-o' 'Gateway' '-D' 'RASPBERRY' '-D' 'DEBUG' '-v' '-shared-libgcc' '-march=armv6' '-mfloat-abi=hard' '-mfpu=vfp'
 as -march=armv6 -mfloat-abi=hard -mfpu=vfp -meabi=5 -o /tmp/ccxS71Nt.o /tmp/cc14Rj3C.s
COMPILER_PATH=/usr/lib/gcc/arm-linux-gnueabihf/4.6/:/usr/lib/gcc/arm-linux-gnueabihf/4.6/:/usr/lib/gcc/arm-linux-gnueabihf/:/usr/lib/gcc/arm-linux-gnueabihf/4.6/:/usr/lib/gcc/arm-linux-gnueabihf/
LIBRARY_PATH=/usr/lib/gcc/arm-linux-gnueabihf/4.6/:/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../arm-linux-gnueabihf/:/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../:/lib/arm-linux-gnueabihf/:/lib/:/usr/lib/arm-linux-gnueabihf/:/usr/lib/
COLLECT_GCC_OPTIONS='-o' 'Gateway' '-D' 'RASPBERRY' '-D' 'DEBUG' '-v' '-shared-libgcc' '-march=armv6' '-mfloat-abi=hard' '-mfpu=vfp'
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/collect2 --sysroot=/ --build-id --no-add-needed --eh-frame-hdr -dynamic-linker /lib/ld-linux-armhf.so.3 -X --hash-style=both -m armelf_linux_eabi -o Gateway /usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../arm-linux-gnueabihf/crt1.o /usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../arm-linux-gnueabihf/crti.o /usr/lib/gcc/arm-linux-gnueabihf/4.6/crtbegin.o -L/usr/lib/gcc/arm-linux-gnueabihf/4.6 -L/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../arm-linux-gnueabihf -L/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../.. -L/lib/arm-linux-gnueabihf -L/usr/lib/arm-linux-gnueabihf /tmp/cchWEJTh.o /tmp/ccxS71Nt.o -lwiringPi -lmosquitto -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /usr/lib/gcc/arm-linux-gnueabihf/4.6/crtend.o /usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../arm-linux-gnueabihf/crtn.o

**Comment by Gizzbert** [comment]
ty for you quick reply
- res value was 1000 ( I think), changed it to 10 and back, still the same msg. It seems to have something to do with mosquitto (mosquitto_connect_callback_set) Will try to get that more verbose.
- The verbose compiling of the gateway gave the followin result:
  edit: removed output
- verbosifying the output of gateway.c gives me:
  Listening at 915 Mhz...setup complete
  connection refused code 1 unacceptable protocol version)
  (code from http://mosquitto.org/api/files/mosquitto-h.html#mosquitto_connect_callback_set)

Upon running the command in the walkthrough in this repo, I run into several glitches installing mosquitto:
sudo wget http://repo.mosquitto.org/debian/mosquitto-stable.list does not exist, so I used the repo-list, so:
sudo wget http://repo.mosquitto.org/debian/mosquitto-repo.list

then I get an error due to a dependency:
The following packages have unmet dependencies:
 libmosquitto-dev : Depends: libmosquitto1 (>= 1.4-0mosquitto2~nows) but 1.3.5-0mosquitto1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Gizzbert** [comment]
got it! 
- I uninstalled mosquitto (1.3.5 has dependency issues I think)
- I installed mosquitto 1.4 following another guide (http://fun-tech.se/FunTechHouse/Mosquitto/index.php#MQTT)
- I cloned the Git (I copied the files via copy/paste earlier) via git clone git://github.com/abouillot/HomeAutomation (adding this to the walkthrough would be helpful for other noobs :)
- uncommented the 915 mhz and commented the 433 Mhz
- recompiled with g++ Gateway.c rfm69.cpp -o Gateway -lwiringPi -lmosquitto -DRASPBERRY -DDEBUG

and Voila:
Listening at 915 Mhz...setup complete
Connect succeed

Yay! Any thoughts on how I make sure my sensor is hooked up properly? Any kind of test available?

thanks

**Comment by mhortman** [comment]
OK here is with -V


pi@raspberrypi ~/HomeAutomation-master/piGateway $ g++ Gateway.c rfm69.cpp -o Gateway -lwiringPi -lmosquitto -DRASPBERRY -DDEBUG -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.6.3-14+rpi1' --with-bugurl=file:///usr/share/doc/gcc                                -4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --                                enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --w                                ith-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enabl                                e-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-s                                jlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabi                                hf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.6.3 (Debian 4.6.3-14+rpi1)
COLLECT_GCC_OPTIONS='-o' 'Gateway' '-D' 'RASPBERRY' '-D' 'DEBUG' '-v' '-shared-libgcc' '-march=armv6' '-mfloat-abi=ha                                rd' '-mfpu=vfp'
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/cc1plus -quiet -v -imultilib . -imultiarch arm-linux-gnueabihf -D_GNU_SOURCE -D                                 RASPBERRY -D DEBUG Gateway.c -quiet -dumpbase Gateway.c -march=armv6 -mfloat-abi=hard -mfpu=vfp -auxbase Gateway -ve                                rsion -o /tmp/ccVUGtFR.s
GNU C++ (Debian 4.6.3-14+rpi1) version 4.6.3 (arm-linux-gnueabihf)
        compiled by GNU C version 4.6.3, GMP version 5.0.5, MPFR version 3.1.0-p10, MPC version 0.9
GGC heuristics: --param ggc-min-expand=59 --param ggc-min-heapsize=55717
ignoring nonexistent directory "/usr/local/include/arm-linux-gnueabihf"
ignoring nonexistent directory "/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../arm-linux-gnueabihf/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/4.6
 /usr/include/c++/4.6/arm-linux-gnueabihf/.
 /usr/include/c++/4.6/backward
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/include
 /usr/local/include
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/include-fixed
 /usr/include/arm-linux-gnueabihf
 /usr/include
End of search list.
GNU C++ (Debian 4.6.3-14+rpi1) version 4.6.3 (arm-linux-gnueabihf)
        compiled by GNU C version 4.6.3, GMP version 5.0.5, MPFR version 3.1.0-p10, MPC version 0.9
GGC heuristics: --param ggc-min-expand=59 --param ggc-min-heapsize=55717
Compiler executable checksum: 64a5da90acce21afabe8e916f286e44e
Gateway.c:65:23: fatal error: mosquitto.h: No such file or directory
compilation terminated.
COLLECT_GCC_OPTIONS='-o' 'Gateway' '-D' 'RASPBERRY' '-D' 'DEBUG' '-v' '-shared-libgcc' '-march=armv6' '-mfloat-abi=ha                                rd' '-mfpu=vfp'
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/cc1plus -quiet -v -imultilib . -imultiarch arm-linux-gnueabihf -D_GNU_SOURCE -D                                 RASPBERRY -D DEBUG rfm69.cpp -quiet -dumpbase rfm69.cpp -march=armv6 -mfloat-abi=hard -mfpu=vfp -auxbase rfm69 -vers                                ion -o /tmp/ccVUGtFR.s
GNU C++ (Debian 4.6.3-14+rpi1) version 4.6.3 (arm-linux-gnueabihf)
        compiled by GNU C version 4.6.3, GMP version 5.0.5, MPFR version 3.1.0-p10, MPC version 0.9
GGC heuristics: --param ggc-min-expand=59 --param ggc-min-heapsize=55717
ignoring nonexistent directory "/usr/local/include/arm-linux-gnueabihf"
ignoring nonexistent directory "/usr/lib/gcc/arm-linux-gnueabihf/4.6/../../../../arm-linux-gnueabihf/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/include/c++/4.6
 /usr/include/c++/4.6/arm-linux-gnueabihf/.
 /usr/include/c++/4.6/backward
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/include
 /usr/local/include
 /usr/lib/gcc/arm-linux-gnueabihf/4.6/include-fixed
 /usr/include/arm-linux-gnueabihf
 /usr/include
End of search list.
GNU C++ (Debian 4.6.3-14+rpi1) version 4.6.3 (arm-linux-gnueabihf)
        compiled by GNU C version 4.6.3, GMP version 5.0.5, MPFR version 3.1.0-p10, MPC version 0.9
GGC heuristics: --param ggc-min-expand=59 --param ggc-min-heapsize=55717
Compiler executable checksum: 64a5da90acce21afabe8e916f286e44e
COLLECT_GCC_OPTIONS='-o' 'Gateway' '-D' 'RASPBERRY' '-D' 'DEBUG' '-v' '-shared-libgcc' '-march=armv6' '-mfloat-abi=ha                                rd' '-mfpu=vfp'
 as -march=armv6 -mfloat-abi=hard -mfpu=vfp -meabi=5 -o /tmp/ccnhIGHd.o /tmp/ccVUGtFR.s

**Comment by abouillot** [comment]
Hi,

According to the output, it seems the mosquitto.h is not found during
compilation:
Gateway.c:65:23: fatal error: mosquitto.h: No such file or directory

Has the mosquitto package properly installed?

I also notice the issue doesn't seem the same as in your first report, as
initially Gateway wasn't able to link with rfm69, while in this case, the
issue seems on the gateway compilation.

Not sure it gives you any hint.

Alexandre

**Comment by dadataman** [comment]
I have the same issue as you had Gizzbert when compiling the Gateway. I tried to follow this guide to upgrade mosquitto: 
(http://fun-tech.se/FunTechHouse/Mosquitto/index.php#MQTT)
 but had trouble with the command: 
xclip -sel clip < ~/.ssh/id_rsa.pub
Error: Can't open display: (null)
I can't seem to copy the key to Github when the clip command don't work. How did you manage?

**Comment by mhortman** [comment]
@Dadataman,
I assume you are going to the FunTechHouse for the same reason that I tried
and failed that route.

The instructions in the abouillot/HomeAutomation refers to a file

http://repo.mosquitto.org/debian/mosquitto-stable.list

That doesn't exist.  So you then went and tried the file on
repo.mosquitt.org/debian/mosquitto-wheezy.list
That installed mosquitto just fine, but you were unable to install
libmosquitto-dev for this project because you got an error:

libmosquitto-dev : Depends: libmosquitto1 (>= 1.4-0mosquitto2~nows) but
1.3.5-0 libmosquitto1 is to be installed

Can anyone help install the correct version of libmosquitto-dev.

the google seems to not be helpful to get libmosquitto-dev installed.

**Comment by Gizzbert** [comment]
Hi, I followed the steps as outlined in my post above. I had an issue with dependency as you state, so uninstalled 1.3.5, then installed 1.4.0 via the funhouse tutorial. I however do remember also installing the following on top (as per http://www.instructables.com/id/Uber-Home-Automation-w-Arduino-Pi/?ALLSTEPS): sudo apt-get install mosquitto mosquitto-clients python-mosquitto which I think adds the correct clients package. 

I did also have an issue with xclip, which led me to generate an SSH key via this tutorial: https://help.github.com/articles/generating-ssh-keys/

hope this helps

**Comment by abouillot** [comment]
Ok, seems the packages at the Debian and Mosquitto repositories have some dependances issues. I'll try to figure out how to address it in an clean way. I've contacted Robert @ mosquitto.org to get some hints.

**Comment by dadataman** [comment]
Thanks for helping!

I tried the FunTechHouse route but that installation destroyed my working mosquitto. I had an error message with this command: ps -A | grep mosq, so that i didn't know how to start mosquitto.
In addition as stated by mhortman, I still got this error message:

libmosquitto-dev : Depends: libmosquitto1 (>= 1.4-0mosquitto2~nows) but
1.3.5-0 libmosquitto1 is to be installed

I reverted back to a previous version of debian 3.12.35+ and it is now working with mosquitto v.1.3.5. A backup that had all the dependances installed but with the issues mentioned below.
The only issues I now have is that mosquitto must be ,running warm, before I can connect the piGateway to it. If I try to run: sudo ./Gateway, immediately after starting mosquitto I get the message:
Setup complete....Listening at 868 Mhz
connection refused
If I wait overnight and start the piGateway I will get: connect succed. I can't tell why.
Also the Gateway still seems to freeze up daily -stop receiving. If I restart it works immediately again

**Comment by abouillot** [comment]
I've published the updated instruction on project page to survive to the current situation. In order to have the service properly installed, I use the packages, but then compile localy the library to be at the same 1.3.5 level as the packages currently provided

**Comment by dadataman** [comment]
Thanks!
I updated the HomeAutomation folder yesterday evening to the newest version. I did follow the previous installation instructions as I had all dependances installed. 
I have noticed that the latest version of the Gateway is more stable -this is the first version I've tried that still was connected the next morning. 
Any suggestions as to why the Gateway will not connect to mosquitto immediately after starting mosquitto?

**Comment by mhortman** [comment]
Thank you.  The new instructions worked, great.  Got it compiling and
running.  On to testing......

**Comment by dadataman** [comment]
After some more testing I still find the gateway disconnects randomly, at ,least once a day. However it seems slightly more stable.
Another minor problem is that I have to wait 7-8 hours after starting mosquitto before I get: connect succed. If I try to connect immediaterly after starting mosquitto I get, connection refused.  
Anyone know how to set a username in the Gateway to identify with mosquitto passwd-file?
As I believe the connection problems is related to not having a username. 
Has anyone else had these problems?

**Comment by joshuarobot1** [comment]
@Dadataman I did have those problems, and it was a result of a bad wire connection. I soldered headers to the RFM chip and ran some cheap pre-crimped wires from the chip to the gpio pins on the PI. it wouldnt connect me until i removed a couple of wires and soon realized one of the wires was broken. once i switched it out i didnt have the issue anymore. it connects almost immediately.

**Comment by dadataman** [comment]
Thanks!
I will check that! I am using dupont female cable to connect to gpio pins. The RFM end is soldered.
Do u mind If I ask where you got the headers for the chip?

**Comment by joshuarobot1** [comment]
those are the same wires i was using and there were a couple of duds in my bunch so it wouldnt surprise me if that was your problem. I am using normal pcb male headers and the direction is staggered every other pin. it looks very crude but i prefer to have the headers instead of soldering wires directly to the chip. it is a bit frustrating that the chip doesnt have standard pcb spaced holes.

**Comment by abouillot** [comment]
I also suffered from bad connection, but usualy, this prevent to reach the 'setup complete' stage.
I saw few time the connection stuck and noticed the bad link can be 'proven' with the Gateway process reaching high percentage of CPU time.

In my case, when the setup complete is display, the connect success  to mosquitto come right after.

Regarding HW setup, I use some proto board where standard pins are connected on one side and the other side goes from the proto-board to the RFM using a wire. Not realy elegant, but allow to swap RFM modules and/or host.

<img src="http://bouillot.org/pics/RFM69_breadBoard.jpg" alt="breadboard" width="200">

**Comment by dadataman** [comment]
Thanks for sharing!
I always reach the 'setup complete' stage when starting the Gateway. If mosquitto is not started I will get 'connect failure'...
My Gateway function as if there is a delay of 8 hours before it can connect to mosquitto, after restarting mosquitto.or rebooting the machine -very strange.
I does not seem related to the Gateway code, but rather my spesific installation.

**Comment by abouillot** [comment]
Compilation issue has been temporary solved, by building the lib by hand.

Closing this one, despite several other topics not directly related to initial post.
