### ISSUE TITLE
No incoming Signal

### ISSUE THREAD

**Issue by mhortman** [abouillot/HomeAutomation#5]
I got the program to compile.  Great instructions.....  Thank you..
My RFM doesn't seem to receive any messages.
I downloaded http://rdepablos.merlitec.com/mixed/rfm69-library-for-raspberry-pi
and ran the test_rfm69 program and was receiving messages just fine.  Same pi.

I rewrote your code to use the c library and at least the receiving portion works and puts the message onto the mqtt just fine.

I would like to stop using my basterdized version, but not quite sure where to go.  any one else have this issue?

I would happily upload my c program if anyone else is having the same issue, but hate to start a branch of a great program.....

**Comment by abouillot** [comment]
The Gateway rely on the interrupt signal on GPIO to know some data are present. Raul solution don't. Maybe the GPIO line is not working properly. it's the one from DID0 to pin 22 (GPIO 25).

Could you put some traces in the RFM69::isr0() function, so we can see if the signal is triggered.

**Comment by mhortman** [comment]
You are pure genius.  Hooking up to pin22 worked just great.  Worked fine
with Raul solution, but now I have yours working.  Much Thanks....

**Comment by abouillot** [comment]
Glad it works now
