### ISSUE TITLE
Need high level documentation

### ISSUE THREAD

**Issue by glassl** [abouillot/HomeAutomation#8]
I'm wondering if you have a high-level description of this home automation solution.  I've read electronichamsters description of his project on instructables. I understand that you're replacing his 2-arduino hub, but I don't understand how.  Are you connecting the RFM69 directly to the Raspberry Pi, or are you connecting it to an arduino that then connects to the Pi?

Thanks

**Comment by vador98** [comment]
This project replaces the arduino gateways in that instructables project with a single raspberry pi. With the piGateway program, you no longer need an arduino to act as the middleman between the rfm69 module, the network, and the raspberry pi. This application is configured to receive messages over rfm, convert them to a mosquito message and then post that message to the mosquito broker. 

—

**Comment by glassl** [comment]
Got it.  piGateway/README.md says to connect SLCK on the RFM to pin 23 on the Pi.  I don't see any SLCK.  Did you mean SCK?

**Comment by mhortman** [comment]
Yes, hooking to SCK worked for me.
