### ISSUE TITLE
sensornode.ino does not compile

### ISSUE THREAD

**Issue by Gizzbert** [abouillot/HomeAutomation#9]
Hi, while verifying the sensornode I get errors on the DHT part of the sketch, I did rename the referenced lib in the sketch to upper case, but stiull get the following errors:

<pre><code>Abouillot_sensornode.ino:72:1: error: 'dht' does not name a type
Abouillot_sensornode.ino: In function 'void loop()':
Abouillot_sensornode.ino:204:14: error: expected primary-expression before '.' token
Abouillot_sensornode.ino:207:6: error: 'DHTLIB_OK' was not declared in this scope
Abouillot_sensornode.ino:210:6: error: 'DHTLIB_ERROR_CHECKSUM' was not declared in this scope
Abouillot_sensornode.ino:213:6: error: 'DHTLIB_ERROR_TIMEOUT' was not declared in this scope
Abouillot_sensornode.ino:216:6: error: 'DHTLIB_ERROR_CONNECT' was not declared in this scope
Abouillot_sensornode.ino:219:6: error: 'DHTLIB_ERROR_ACK_L' was not declared in this scope
Abouillot_sensornode.ino:222:6: error: 'DHTLIB_ERROR_ACK_H' was not declared in this scope
Abouillot_sensornode.ino:229:15: error: expected primary-expression before '.' token
Abouillot_sensornode.ino:231:15: error: expected primary-expression before '.' token
Error compiling.</code></pre>

This looks like a library error, so I added the adafruit lib, but to no avail, anyone else have this error?

thanks

**Comment by abouillot** [comment]
Hi,

I cross two variants of the DHT lib.  I cannot remember why I used one
over the other. But it looks like you use the other one.

**Comment by Gizzbert** [comment]
its this one for the record: https://github.com/RobTillaart/Arduino/tree/master/libraries/DHTlib
